Class {
	#name : #XSDComplexFinal,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDComplexFinal class >> all [
	^ self on: #all

]

{ #category : #'accessing - enum' }
XSDComplexFinal class >> extension [
	^ self on: #extension

]

{ #category : #'accessing - enum' }
XSDComplexFinal class >> restriction [
	^ self on: #restriction

]

{ #category : #'accessing - enum' }
XSDComplexFinal >> all [
	^ self on: #all

]

{ #category : #'accessing - enum' }
XSDComplexFinal >> extension [
	^ self on: #extension

]

{ #category : #'accessing - enum' }
XSDComplexFinal >> restriction [
	^ self on: #restriction

]
