Class {
	#name : #XSDCompositor,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDCompositor class >> all [
	^ self on: #all

]

{ #category : #'accessing - enum' }
XSDCompositor class >> choice [
	^ self on: #choice

]

{ #category : #'accessing - enum' }
XSDCompositor class >> sequence [
	^ self on: #sequence

]

{ #category : #'accessing - enum' }
XSDCompositor >> all [
	^ self on: #all

]

{ #category : #'accessing - enum' }
XSDCompositor >> choice [
	^ self on: #choice

]

{ #category : #'accessing - enum' }
XSDCompositor >> sequence [
	^ self on: #sequence

]
