Class {
	#name : #XSDContentTypeCategory,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDContentTypeCategory class >> elementOnly [
	^ self on: #elementOnly

]

{ #category : #'accessing - enum' }
XSDContentTypeCategory class >> empty [
	^ self on: #empty

]

{ #category : #'accessing - enum' }
XSDContentTypeCategory class >> mixed [
	^ self on: #mixed

]

{ #category : #'accessing - enum' }
XSDContentTypeCategory class >> simple [
	^ self on: #simple

]

{ #category : #'accessing - enum' }
XSDContentTypeCategory >> elementOnly [
	^ self on: #elementOnly

]

{ #category : #'accessing - enum' }
XSDContentTypeCategory >> empty [
	^ self on: #empty

]

{ #category : #'accessing - enum' }
XSDContentTypeCategory >> mixed [
	^ self on: #mixed

]

{ #category : #'accessing - enum' }
XSDContentTypeCategory >> simple [
	^ self on: #simple

]
