Class {
	#name : #XSDDisallowedSubstitutions,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDDisallowedSubstitutions class >> all [
	^ self on: #all

]

{ #category : #'accessing - enum' }
XSDDisallowedSubstitutions class >> extension [
	^ self on: #extension

]

{ #category : #'accessing - enum' }
XSDDisallowedSubstitutions class >> restriction [
	^ self on: #restriction

]

{ #category : #'accessing - enum' }
XSDDisallowedSubstitutions class >> substitution [
	^ self on: #substitution

]

{ #category : #'accessing - enum' }
XSDDisallowedSubstitutions >> all [
	^ self on: #all

]

{ #category : #'accessing - enum' }
XSDDisallowedSubstitutions >> extension [
	^ self on: #extension

]

{ #category : #'accessing - enum' }
XSDDisallowedSubstitutions >> restriction [
	^ self on: #restriction

]

{ #category : #'accessing - enum' }
XSDDisallowedSubstitutions >> substitution [
	^ self on: #substitution

]
