Class {
	#name : #XSDForm,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDForm class >> qualified [
	^ self on: #qualified

]

{ #category : #'accessing - enum' }
XSDForm class >> unqualified [
	^ self on: #unqualified

]

{ #category : #'accessing - enum' }
XSDForm >> qualified [
	^ self on: #qualified

]

{ #category : #'accessing - enum' }
XSDForm >> unqualified [
	^ self on: #unqualified

]
