Class {
	#name : #XSDIdentityConstraintCategory,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDIdentityConstraintCategory class >> key [
	^ self on: #key

]

{ #category : #'accessing - enum' }
XSDIdentityConstraintCategory class >> keyref [
	^ self on: #keyref

]

{ #category : #'accessing - enum' }
XSDIdentityConstraintCategory class >> unique [
	^ self on: #unique

]

{ #category : #'accessing - enum' }
XSDIdentityConstraintCategory >> key [
	^ self on: #key

]

{ #category : #'accessing - enum' }
XSDIdentityConstraintCategory >> keyref [
	^ self on: #keyref

]

{ #category : #'accessing - enum' }
XSDIdentityConstraintCategory >> unique [
	^ self on: #unique

]
