Class {
	#name : #XSDNamespaceConstraintCategory,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDNamespaceConstraintCategory class >> any [
	^ self on: #any

]

{ #category : #'accessing - enum' }
XSDNamespaceConstraintCategory class >> not [
	^ self on: #not

]

{ #category : #'accessing - enum' }
XSDNamespaceConstraintCategory class >> set [
	^ self on: #set

]

{ #category : #'accessing - enum' }
XSDNamespaceConstraintCategory >> any [
	^ self on: #any

]

{ #category : #'accessing - enum' }
XSDNamespaceConstraintCategory >> not [
	^ self on: #not

]

{ #category : #'accessing - enum' }
XSDNamespaceConstraintCategory >> set [
	^ self on: #set

]
