Class {
	#name : #XSDOrdered,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDOrdered class >> false [
	^ self on: #false

]

{ #category : #'accessing - enum' }
XSDOrdered class >> partial [
	^ self on: #partial

]

{ #category : #'accessing - enum' }
XSDOrdered class >> total [
	^ self on: #total

]

{ #category : #'accessing - enum' }
XSDOrdered >> false [
	^ self on: #false

]

{ #category : #'accessing - enum' }
XSDOrdered >> partial [
	^ self on: #partial

]

{ #category : #'accessing - enum' }
XSDOrdered >> total [
	^ self on: #total

]
