Class {
	#name : #XSDProcessContents,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDProcessContents class >> lax [
	^ self on: #lax

]

{ #category : #'accessing - enum' }
XSDProcessContents class >> skip [
	^ self on: #skip

]

{ #category : #'accessing - enum' }
XSDProcessContents class >> strict [
	^ self on: #strict

]

{ #category : #'accessing - enum' }
XSDProcessContents >> lax [
	^ self on: #lax

]

{ #category : #'accessing - enum' }
XSDProcessContents >> skip [
	^ self on: #skip

]

{ #category : #'accessing - enum' }
XSDProcessContents >> strict [
	^ self on: #strict

]
