Class {
	#name : #XSDProhibitedSubstitutions,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDProhibitedSubstitutions class >> all [
	^ self on: #all

]

{ #category : #'accessing - enum' }
XSDProhibitedSubstitutions class >> extension [
	^ self on: #extension

]

{ #category : #'accessing - enum' }
XSDProhibitedSubstitutions class >> restriction [
	^ self on: #restriction

]

{ #category : #'accessing - enum' }
XSDProhibitedSubstitutions >> all [
	^ self on: #all

]

{ #category : #'accessing - enum' }
XSDProhibitedSubstitutions >> extension [
	^ self on: #extension

]

{ #category : #'accessing - enum' }
XSDProhibitedSubstitutions >> restriction [
	^ self on: #restriction

]
