Class {
	#name : #XSDSimpleFinal,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDSimpleFinal class >> all [
	^ self on: #all

]

{ #category : #'accessing - enum' }
XSDSimpleFinal class >> list [
	^ self on: #list

]

{ #category : #'accessing - enum' }
XSDSimpleFinal class >> restriction [
	^ self on: #restriction

]

{ #category : #'accessing - enum' }
XSDSimpleFinal class >> union [
	^ self on: #union

]

{ #category : #'accessing - enum' }
XSDSimpleFinal >> all [
	^ self on: #all

]

{ #category : #'accessing - enum' }
XSDSimpleFinal >> list [
	^ self on: #list

]

{ #category : #'accessing - enum' }
XSDSimpleFinal >> restriction [
	^ self on: #restriction

]

{ #category : #'accessing - enum' }
XSDSimpleFinal >> union [
	^ self on: #union

]
