Class {
	#name : #XSDSubstitutionGroupExclusions,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDSubstitutionGroupExclusions class >> extension [
	^ self on: #extension

]

{ #category : #'accessing - enum' }
XSDSubstitutionGroupExclusions class >> restriction [
	^ self on: #restriction

]

{ #category : #'accessing - enum' }
XSDSubstitutionGroupExclusions >> extension [
	^ self on: #extension

]

{ #category : #'accessing - enum' }
XSDSubstitutionGroupExclusions >> restriction [
	^ self on: #restriction

]
