Class {
	#name : #XSDWhiteSpace,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDWhiteSpace class >> collapse [
	^ self on: #collapse

]

{ #category : #'accessing - enum' }
XSDWhiteSpace class >> preserve [
	^ self on: #preserve

]

{ #category : #'accessing - enum' }
XSDWhiteSpace class >> replace [
	^ self on: #replace

]

{ #category : #'accessing - enum' }
XSDWhiteSpace >> collapse [
	^ self on: #collapse

]

{ #category : #'accessing - enum' }
XSDWhiteSpace >> preserve [
	^ self on: #preserve

]

{ #category : #'accessing - enum' }
XSDWhiteSpace >> replace [
	^ self on: #replace

]
