Class {
	#name : #XSDXPathVariety,
	#superclass : #XSDEnum,
	#category : #'XSD-Metamodel-Enumerations'
}

{ #category : #'accessing - enum' }
XSDXPathVariety class >> field [
	^ self on: #field

]

{ #category : #'accessing - enum' }
XSDXPathVariety class >> selector [
	^ self on: #selector

]

{ #category : #'accessing - enum' }
XSDXPathVariety >> field [
	^ self on: #field

]

{ #category : #'accessing - enum' }
XSDXPathVariety >> selector [
	^ self on: #selector

]
